# Generated by Django 4.1.1 on 2022-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentform_roll_number_studentform_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('ps_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('ps_pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('ps_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('understanding', models.CharField(blank=True, max_length=2000, null=True)),
                ('approach', models.CharField(blank=True, max_length=2000, null=True)),
                ('commitments', models.CharField(blank=True, max_length=2000, null=True)),
                ('topskills', models.CharField(blank=True, max_length=2000, null=True)),
                ('skills', models.CharField(blank=True, max_length=2000, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='studentform',
            old_name='file',
            new_name='resume',
        ),
    ]
