# Generated by Django 4.1.1 on 2022-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_problem_registration_rename_file_studentform_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
