# Generated by Django 4.1.1 on 2022-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ps_id',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='roll_number',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
