# Generated by Django 4.1.1 on 2022-12-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_problem_ps_id_alter_studentform_roll_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table=None,
        ),
    ]
