# Generated by Django 4.1.1 on 2022-12-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_registration_deadline_problem_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_dead',
            field=models.DateField(blank=True, null=True),
        ),
    ]
