# Generated by Django 3.0.5 on 2022-12-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20221223_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
