# Generated by Django 3.0.5 on 2022-12-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221224_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ldap',
            field=models.CharField(blank=True, default='null', max_length=2000, null=True),
        ),
    ]
